# What is NumPy ?
NumPy stands for numerical python.NumPy is a python library used for working with arrays. NumPy was created in 2005 by Travis Oliphant. It is a open source project and we can use it freely.
Users:- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.23.5'

In [4]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [5]:
type(arr)

numpy.ndarray

In [5]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [7]:
type(arr1)

numpy.ndarray

In [10]:
arr_2d=np.array([[4,5,6],[7,8,9]])
print(arr_2d)

[[4 5 6]
 [7 8 9]]


In [12]:
type(arr_2d)

numpy.ndarray

In [16]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# 1D array indexing

In [17]:
a=np.array([1,2,3,4,5,6])
print(a[0])

1


In [18]:
a=np.array([1,2,3,4,5,6])
print(a[-1])

6


In [19]:
print(a[-3])

4


# 2D array indexing

In [3]:
arr_0= np.array([[1,2,3],[4,5,6]])
print(arr_0)

[[1 2 3]
 [4 5 6]]


In [20]:
print(arr_2d[0,1])

5


In [23]:
print(arr_2d[-1,-1])

9


# 3D array indexing

In [35]:
print(arr_3d[1,1])

[10 11 12]


# Slicing

In [29]:
arr=np.array([1,2,3,4,5,6])
print(arr[3:5])

[4 5]


In [33]:
arra=np.array([[1,2,3],[4,5,6]])
print(arra[0:2,1])

[2 5]


In [36]:
print(arra[0:2,2])

[3 6]


In [37]:
print(arra[1:2,1])

[5]


In [40]:
b=np.array([[1,2,5,6,7,8,9],[11,12,10,5,6,8,10],[14,15,18,20,21,22,23],[10,7,8,7,9,10,23]])
print(b)

[[ 1  2  5  6  7  8  9]
 [11 12 10  5  6  8 10]
 [14 15 18 20 21 22 23]
 [10  7  8  7  9 10 23]]


In [42]:
print(b[1,1:4])

[12 10  5]


In [45]:
print(b[2:4,2:4])

[[18 20]
 [ 8  7]]


In [46]:
print(b[1:4,0:2])

[[11 12]
 [14 15]
 [10  7]]


# Data Types in NumPy

In [6]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [7]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


# Converting Data Type on Existing Arrays

In [8]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [9]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [10]:
#shape
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


In [11]:
#reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
#concatenate
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [14]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
#splite
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [17]:
#search- in value
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [18]:
#search in index=
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [19]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [20]:
from numpy import random
x = random.randint(100)

print(x)

94


In [21]:
x = random.rand()

print(x)

0.4026418075043209


In [22]:
x=random.randint(100, size=(6))

print(x)

[ 2 19 80 66 59 92]


In [23]:
x = random.randint(100, size=(4, 5))

print(x)

[[62 11 12 78 81]
 [63 51 47 30  5]
 [91 50 76 96 90]
 [58 72 53 90 49]]


In [24]:
x = random.choice([3, 5, 7, 9])

print(x)

9


In [25]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 3 3 3]
 [9 3 7 5 9]
 [7 3 7 5 9]]


In [26]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 1 3 5 4]


In [27]:
#The permutation() method returns a re-arranged array
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[5 1 4 2 3]


# NumPy ufuncs
What are ufuncs?


ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [28]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    
    z.append(i + j)
print(z)

[5, 7, 9, 11]


In [29]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [30]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [31]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [32]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [33]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [34]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [35]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [36]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [37]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# Rounding Decimals
<pre>
There are primarily five ways of rounding off decimals in NumPy:

truncation
fix
rounding
floor
ceil

# Truncation

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [38]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


# Rounding

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

In [40]:
arr = np.around(3.1666, 2)

print(arr)

3.17


# Floor
The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.

# Ceil
The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 4.

In [42]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [43]:
arr = np.arange(1, 10)

print(np.log2(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [44]:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [45]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [46]:
#To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [47]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [48]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [49]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [50]:
x = np.sin(np.pi/2)

print(x)

1.0


In [51]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [52]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]
